name: Otomatik APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Java ve Sistem Paketlerini Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev libffi-dev libmpdec-dev libexpat1-dev liblzma-dev uuid-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Buildozer ile APK Derle
        run: |
          export PATH=$PATH:~/.local/bin
          # 'yes |' komutu sayesinde buildozer çalışırken lisans sorarsa otomatik 'y' basılacak
          yes | buildozer -v android debug
        env:
          BUILDOZER_ALLOW_KIVY_NEW_DESIGN: 1

      - name: APK'yi Sisteme Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Yapay_Zeka_Oyun_Asistani
          path: bin/*.apk
